import csv
import panphon
ft = panphon.FeatureTable()

def load_languages_for_cleanup(filename, delimiter=','):
    languages = []
    with open(filename, encoding = 'utf-8') as f:
        reader = None
        reader = csv.reader(f, delimiter=delimiter)
        header_row = next(reader)
        header_len = len(header_row)
        for row in reader:
            if len(row) != len(header_row):
                print("row of length", len(row),
                      "does not match, header of length", header_len)
            else:
                languages.append(row)
    f.close()
    return languages

def cleanup(infile, outfile):
    with open(infile, encoding = 'utf-8') as f1:
        reader = csv.reader(f1)
        header_row = next(reader)
        with open(outfile, mode='w', encoding = 'utf-8', newline = '\n') as f2:
            writer = csv.writer(f2, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            writer.writerow(header_row)
            for row in reader:
                print("Cleaning up row of length",str(len(row)),
                      'first entry is of length',str(len(row[0])))
                clean_row = [row[0]]
                #i=0
                for term in row[1:]:
                    #if i<10:
                    #    print(term)
                    #    i+=1
                    clean_row.append(to_ipa(term))
                writer.writerow(clean_row)

def to_ipa(term):
    term = term.replace('g', 'ɡ')
    term = term.replace('è', 'e')
    term = term.replace('ī', 'i')
    if 'ĕ' in term:
        print("Here")
    term = term.replace('ĕ', 'e')
    term = term.replace('ā', 'a')
    term = term.replace('ě', 'e')
    term = term.replace('ū', 'u')
    term = term.replace('á', 'a')
    term = term.replace('í', 'i')
    term = term.replace('é', 'e')
    term = term.replace('ú', 'u')
    term = term.replace('ó', 'o')
    term = term.replace('L', 'ʟ')
    term = term.replace('D', 'ð')
    term = term.replace('ń', 'ɲ')
    term = term.replace('à', 'a')
    term = term.replace('č', 't͡ʃ')
    term = term.replace('ị', 'i')
    term = term.replace('ē', 'e')
    term = term.replace('ō', 'o')
    term = term.replace('ḏ', 'd̪')
    term = term.replace('ḇ', 'b')
    term = term.replace('ñ', 'ɲ')
    term = term.replace('ã', 'a') 
    term = term.replace('å', 'ɔ')
    term = term.replace('ũ', 'u')
    term = term.replace('Ĩ', 'ɪ')
    term = term.replace('š', 'ʃ')
    term = term.replace('ĩ', 'i')
    term = term.replace('ḍ', 'ɖ')
    term = term.replace('ṭ', 'ʈ')
    term = term.replace('ḡ', 'ɡ') 
    term = term.replace('I', 'ɪ')
    term = term.replace('û', 'u')
    term = term.replace('ǥ', 'ɡ')
    term = term.replace('ă', 'a')
    term = term.replace('ï', 'i')
    term = term.replace('ì', 'i')
    term = term.replace('ò', 'o')
    term = term.replace('â', 'a')
    term = term.replace('ř', 'ɽ')
    term = term.replace('ṿ', 'v')
    term = term.replace('ṇ', 'ɳ')
    term = term.replace('ǵ', 'ɟ')
    term = term.replace('ḷ', 'l')
    term = term.replace('ḳ', 'k')
    term = term.replace('ü', 'y')
    term = term.replace('î', 'i')
    term = term.replace('ê', 'e')
    term = term.replace('ô', 'o')
    term = term.replace('ë', 'e')
    term = term.replace('ö', 'œ')
    term = term.replace('ä', 'æ')
    term = term.replace('ǎ', 'a')
    term = term.replace('ụ', 'u')
    term = term.replace('ǰ', 'd͡ʒ')
    term = term.replace('N', 'ŋ')
    term = term.replace('ǔ', 'u')
    term = term.replace('ů', 'u̥')
    term = term.replace('ȯ', 'o')
    term = term.replace('ė', 'e')
    term = term.replace('õ', 'o')
    term = term.replace('ʡ', 'ʔ')
    term = term.replace('ṱ', 't̪')
    term = term.replace('ạ', 'a')
    term = term.replace('ĵ', 'd͡ʒ')
    term = term.replace('ù', 'u')
    term = term.replace('ŏ', 'o')
    term = term.replace('ļ', 'ʎ')
    term = term.replace('ṃ', 'm')
    term = term.replace('ņ', 'ɲ')
    term = term.replace('ĭ', 'i')
    term = term.replace('ǒ', 'o')
    term = term.replace('ţ', 't͡s')
    term = term.replace('ß', 'β')
    term = term.replace('ṣ', 'ʂ')
    term = term.replace('ṵ', 'u')
    term = term.replace('ŭ', 'u')
    term = term.replace('ŝ', 'ʃ')
    term = term.replace('O', 'ɔ')
    term = term.replace('ẓ', 'ʒ')
    term = term.replace('?', 'ʔ')
    term = term.replace('ż', 'ʒ')
    term = term.replace('S', 'ʃ')
    term = term.replace('C', 't͡ʃ')
    term = term.replace('M', 'm')
    term = term.replace('J', 'd͡ʒ')
    term = term.replace('ʤ', 'd͡ʒ')
    term = term.replace('ṛ', 'r')
    term = term.replace('W', 'w')
    term = term.replace('P', 'ɸ')
    term = term.replace('A', 'æ')
    term = term.replace('ọ', 'o')
    term = term.replace('ồ', 'o')
    term = term.replace('ề', 'e')
    term = term.replace('T', 'θ')
    term = term.replace('Φ', 'ɸ')
    term = term.replace('V', 'ʌ')
    term = term.replace('U', 'ʌ')
    term = term.replace('B', 'β')
    term = term.replace('K', 'k')
    term = term.replace('R', 'ʁ')
    term = term.replace('ç', 't͡ʃ')
    term = term.replace('μ', 'm')
    term = term.replace('ȳ', 'y')
    term = term.replace('G', 'ɣ')
    term = term.replace('ǣ', 'æ')
    term = term.replace('ɚ', 'ə')
    term = term.replace('ž', 'ʒ')
    term = term.replace('ϑ', 'θ')
    term = term.replace('Ө', 'θ')
    term = term.replace('ć', 't͡ʃ')
    term = term.replace('ȥ', 'ʒ')
    term = term.replace('ẽ', 'e')
    term = term.replace('ǝ', 'ə')
    term = term.replace('ƞ', 'ɲ')
    term = term.replace('ʧ', 't͡ʃ')
    term = term.replace('ả', 'a')
    term = term.replace('đ', 'ð')
    term = term.replace('ư', 'u')
    term = term.replace('ờ', 'o')
    term = term.replace('ế', 'e')
    term = term.replace('ơ', 'o')
    term = term.replace('ẩ', 'a')
    term = term.replace('ộ', 'o')
    term = term.replace('ự', 'u')
    term = term.replace('ợ', 'o')
    term = term.replace('ầ', 'a')
    term = term.replace('ổ', 'o')
    term = term.replace('ở', 'o')
    term = term.replace('ệ', 'e')
    term = term.replace('ỡ', 'o')
    term = term.replace('ử', 'u')
    term = term.replace('ấ', 'a')
    term = term.replace('ố', 'o')
    term = term.replace('ắ', 'a')
    term = term.replace('ủ', 'u')
    term = term.replace('ằ', 'a')
    term = term.replace('ứ', 'u')
    term = term.replace('ậ', 'a')
    term = term.replace('ẻ', 'e')
    term = term.replace('ỗ', 'o')
    term = term.replace('ễ', 'e')
    term = term.replace('ỏ', 'o')
    term = term.replace('ớ', 'o')
    term = term.replace('ể', 'e')
    term = term.replace('ừ', 'u')
    term = term.replace('ặ', 'a')
    term = term.replace('ẹ', 'e')
    term = term.replace('X', 'χ')
    term = term.replace('ȶ', 't̪ʲ')
    term = term.replace('ȵ', 'ɲ')
    term = term.replace('ʨ', 't͡ɕ')#checkpoint
    #Junsung
    term = term.replace('ή','i')
    term = term.replace('ş', 'ʃ')
    term = term.replace('π', 'p')
    term = term.replace('κ', 'k')
    term = term.replace('τ', 't')
    term = term.replace('к', 'k')
    term = term.replace('т', 't')
    term = term.replace('ә', 'ə')
    term = term.replace('ḻ', 'l')
    term = term.replace('ȡ', 'd̪ʲ')
    term = term.replace('Z', 'z')
    term = term.replace('H', 'h')
    term = term.replace('ś', 'ʃ')
    term = term.replace('ȃ', 'ə')
    term = term.replace('ȕ', 'u')
    term = term.replace('ȁ', 'ɐ')
    term = term.replace('ȋ', 'i')
    term = term.replace('ȉ', 'i')
    term = term.replace('ȇ', 'e')
    term = term.replace('Q', 'q')
    term = term.replace('ṫ', 't')
    term = term.replace('ḋ', 'd')
    term = term.replace('E', 'e')
    term = term.replace('Ɂ', 'ʔ')
    term = term.replace('ɷ', 'ʊ')
    term = term.replace('Y', 'y')
    term = term.replace('ɿ', 'z')
    term = term.replace('ʣ','d⁀z')
    term = term.replace('ʥ','d⁀ʑ')
    term = term.replace('ǐ', 'i')
    term = term.replace('ᶇ', 'i')
    term = term.replace('ŗ', 'rʲ')
    term = term.replace('ʆ', 'ʃ')
    term = term.replace('ȴ', 'l')
    term = term.replace('ʦ', 't⁀s')
    term = term.replace('ḭ','ɨ')
    term = term.replace('ḛ', 'ɛ')
    term = term.replace('ᴀ', 'a')
    term = term.replace('ʅ', 'ʐ̩')
    term = term.replace('ǳ', 'd⁀z')
    term = term.replace('&', 'ɶ')
    term = term.replace('ṁ', 'm')
    term = term.replace('ý', 'iː')
    #End of Junsung's code
    term = term.replace('ṅ','n')
    term = term.replace('ᴘ','ʀ')
    term = term.replace('ᴩ','ʀ')
    term = term.replace('ƥ','ɓ')
    term = term.replace('Ì','ɪ')
    term = term.replace('@','æ')
    term = term.replace('ө','ɵ')
    term = term.replace('Ɵ','θ')
    term = term.replace('ő','o')
    term = term.replace('р','p')
    term = term.replace('É','ɛ')
    term = term.replace('Í','ɪ')
    term = term.replace('ԑ','ɛ')
    term = term.replace('Ɉ','ɟ')
    term = term.replace('ҫ','s')
    return term 
                    

if __name__ == '__main__':
    infile = "abvd_lang.csv"
    outfile = "abvd_lang_ipa.csv"
    cleanup(infile,outfile)
    #languages = load_languages_for_cleanup('abvd_lang.csv')
    segs = sorted(ft.seg_dict.keys(), key=lambda x: len(x), reverse=True)
    """list_of_bad_characters = []
    for language in languages:
        for word in language[1:]:
            for character in word:
                if not character in segs and not character in list_of_bad_characters:
                    list_of_bad_characters.append(character)
    print(list_of_bad_characters)"""
                
