from node import Node
n0 = Node('Atayalic')
n1 = Node('NorthWestF')
n2 = Node('NorthernF')
n2.insert_left(n0)
n2.insert_right(n1)
n3 = Node('Kavalanic')
n4 = Node('Ami')
n5 = Node('EasternF')
n5.insert_left(n3)
n5.insert_right(n4)
n6 = Node('Formosan')
n6.insert_left(n2)
n6.insert_right(n5)
n7 = Node('Philippine')
n8 = Node('Sama-Bajaw')
n9 = Node('WesternMP')
n9.insert_left(n7)
n9.insert_right(n8)
n10 = Node('Sumb-Flores')
n11 = Node('Oceanic')
n12 = Node('Central-EasternMP')
n12.insert_left(n10)
n12.insert_right(n11)
n13 = Node('Malayo Polynesian')
n13.insert_left(n9)
n13.insert_right(n12)
n14 = Node('Austronesian lang')
n14.insert_left(n6)
n14.insert_right(n13)

print(n14)
